### ISSUE TITLE
Can you PLEASE make /ctb stay on across sessions?

### ISSUE THREAD

**Issue by Sanwi** [citadel/citadel#94]
It's so annoying to have to check whether or not /ctb is on every time I relog. I used to have a macro that just typed it when I logged in, but sometimes it's saved across sessions now. It's annoying as fuck; I had to make a macro that types /ctb, reads chat to see if it turned on or off, then does it again if it needs to.

**Comment by tombee** [comment]
@Sanwi I think you might have posted this issue on the wrong project :smile: 

Perhaps you're looking for https://github.com/Exultant/Citadel instead?

**Comment by Sanwi** [comment]
I'm so sorry! Thanks for pointing me in the right direction.

**Comment by tombee** [comment]
@Sanwi No problem :smile:
